# Banco de produção
spring.datasource.url=jdbc:postgresql://prod-db:5432/inspectron
spring.datasource.username=prod_user
spring.datasource.password=prod_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Produção: logs mínimos
spring.jpa.show-sql=false
logging.level.root=WARN