# Banco local (dev)
spring.datasource.url=jdbc:postgresql://localhost:5449/inspectron
spring.datasource.username=postgres
spring.datasource.password=pass123
spring.datasource.driver-class-name=org.postgresql.Driver