spring.application.name=inspectron

# Hibernate
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Ativar profile se nada for informado
spring.profiles.active=dev

# JWT defaults (override in secure environments)
app.security.jwt.secret=change-me-access-secret-please-123456
app.security.jwt.assets-secret=change-me-assets-secret-123456
app.security.jwt.first-access-secret=change-me-first-access-secret-123
app.security.jwt.access-token-expiration=PT24H
app.security.jwt.remember-me-access-token-expiration=PT168H
app.security.jwt.first-access-token-expiration=PT10M
