spring.application.name=inspectron

# Hibernate
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Ativar profile se nada for informado
spring.profiles.active=dev
