# Banco de homologação
spring.datasource.url=jdbc:postgresql://homolog-db:5432/inspectron
spring.datasource.username=homolog_user
spring.datasource.password=homolog_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Ajustes específicos de homolog
spring.jpa.show-sql=false
logging.level.root=INFO